#!/usr/bin/env bash
# Register an extracted GitHub Actions Runner on macOS or Linux.
# Run this as the dedicated non-root runner account from the directory that
# contains config.sh and svc.sh.

set -euo pipefail

usage() {
  cat <<'EOF'
Usage:
  register-unix-runner.sh --url URL --token TOKEN --name NAME --labels LABELS [options]

Required:
  --url URL          GitHub repository or organization URL
  --token TOKEN      Short-lived token generated by GitHub's runner page
  --name NAME        Unique runner name
  --labels LABELS    Comma-separated labels, for example acefox,macos,arm64

Optional:
  --work DIRECTORY   Work directory, default: _work
  --service-user USER
                     Account for the launchd/systemd service; default: current user
  --no-service       Register only; run ./run.sh manually afterward
  -h, --help         Show this help
EOF
}

runner_url=''
runner_token=''
runner_name=''
runner_labels=''
runner_work='_work'
service_user="$(id -un)"
install_service=true

while [[ $# -gt 0 ]]; do
  case "$1" in
    --url) runner_url="${2:?missing value for --url}"; shift 2 ;;
    --token) runner_token="${2:?missing value for --token}"; shift 2 ;;
    --name) runner_name="${2:?missing value for --name}"; shift 2 ;;
    --labels) runner_labels="${2:?missing value for --labels}"; shift 2 ;;
    --work) runner_work="${2:?missing value for --work}"; shift 2 ;;
    --service-user) service_user="${2:?missing value for --service-user}"; shift 2 ;;
    --no-service) install_service=false; shift ;;
    -h|--help) usage; exit 0 ;;
    *) echo "Unknown argument: $1" >&2; usage >&2; exit 2 ;;
  esac
done

for variable in runner_url runner_token runner_name runner_labels; do
  if [[ -z "${!variable}" ]]; then
    echo "Missing required option: $variable" >&2
    usage >&2
    exit 2
  fi
done

if [[ "$(id -u)" -eq 0 ]]; then
  echo 'Run registration as the dedicated non-root runner account, not root.' >&2
  exit 1
fi

if [[ ! -x ./config.sh ]]; then
  echo 'config.sh is missing. Run this from the extracted runner directory.' >&2
  exit 1
fi

if [[ -e .runner ]]; then
  echo 'This runner directory is already configured. Remove or replace it in GitHub before re-registering.' >&2
  exit 1
fi

# Do not echo the token. config.sh stores only the runner credential required
# for the service to poll GitHub Actions.
./config.sh \
  --unattended \
  --url "$runner_url" \
  --token "$runner_token" \
  --name "$runner_name" \
  --labels "$runner_labels" \
  --work "$runner_work"

# Recent runner packages generate svc.sh during configuration from the
# platform-specific template, so it must be checked only after config.sh.
if [[ ! -x ./svc.sh ]]; then
  echo 'Runner configuration did not create svc.sh; cannot install the service.' >&2
  exit 1
fi

if [[ "$install_service" == false ]]; then
  echo 'Runner registered. Start it interactively with: ./run.sh'
  exit 0
fi

sudo ./svc.sh install "$service_user"
sudo ./svc.sh start
sudo ./svc.sh status
echo "Runner '$runner_name' is registered and started."
